# **Importing the dataset**

## Digital Music

In [24]:
import pandas as pd

# Load a JSON file into a pandas DataFrame
df = pd.read_json('/content/Digital_Music_5.json', lines=True)

print(f"The DataFrame has {df.shape[0]} rows and {df.shape[1]} columns.")

The DataFrame has 169781 rows and 12 columns.

In [17]:
# Randomly sample 15,000 rows
df_sampled = df.sample(n=15000, random_state=42) # Using random_state for reproducibility

print(f"The sampled DataFrame has {df_sampled.shape[0]} rows and {df_sampled.shape[1]} columns.")
df_sampled.head()

The sampled DataFrame has 15000 rows and 12 columns.

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image
89071,5,NaN,True,"10 23, 2014",A2C2S9BBPWTK9Y,B00CZF8B68,{'Format:': ' MP3 Music'},Suzi,"Love the movie, and especially the song!",Five Stars,1414022400,NaN
131119,5,NaN,False,"12 31, 2015",AQR5ZB4BIJFLT,B00122Z6ZY,{'Format:': ' MP3 Music'},jackie,"Sigh, so good!",so good!,1451520000,NaN
116727,5,NaN,True,"04 18, 2016",A3QEOGJXHI6UEG,B0186SEPNU,{'Format:': ' MP3 Music'},Irene Garcia,Love the foo fighters,Five Stars,1460937600,NaN
76480,5,NaN,True,"12 3, 2014",A18REVWRZ4GA7M,B007JCPEVM,{'Format:': ' MP3 Music'},wendy kipp,1,Five Stars,1417564800,NaN
160338,5,NaN,True,"02 11, 2015",A2IJCEG2J34W61,B00E67KLDE,{'Format:': ' MP3 Music'},Honest Critique,Great Song.,Five Stars,1423612800,NaN

In [18]:
# Count the distribution of 'overall' ratings
rating_distribution = df_sampled['overall'].value_counts().sort_index()

print("Distribution of Overall Ratings:")
print(rating_distribution)

Distribution of Overall Ratings:
overall
1      191
2      156
3      606
4     2037
5    12010
Name: count, dtype: int64

In [14]:
# drop all columns except the id review text and overall
df_sampled_2 = df_sampled[['overall', 'reviewText']]
df_sampled_2.head()

        overall                                reviewText
89071         5  Love the movie, and especially the song!
131119        5                            Sigh, so good!
116727        5                     Love the foo fighters
76480         5                                         1
160338        5                               Great Song.

# Luxury Beauty

In [27]:
import pandas as pd

# Load a JSON file into a pandas DataFrame
df2 = pd.read_json('/content/Luxury_Beauty_5.json', lines=True)

print(f"/nThe DataFrame has {df2.shape[0]} rows and {df2.shape[1]} columns.")

/nThe DataFrame has 34278 rows and 12 columns.

In [28]:
# Randomly sample 15,000 rows
df2_sampled = df2.sample(n=15000, random_state=42) # Using random_state for reproducibility

print(f"The sampled DataFrame has {df2_sampled.shape[0]} rows and {df2_sampled.shape[1]} columns.")
df2_sampled.head()

The sampled DataFrame has 15000 rows and 12 columns.

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
27291,4,False,"11 8, 2016",A28I98PKHZZKVB,B00NM75BX4,NaN,S.Trasny,DH got his first bottle of Baxter of Californi...,2nd To Baxter's Super Close Shave Formula,1478563200,NaN,NaN
16095,5,True,"09 3, 2013",AQO3WDKL8Q7BL,B004N2SQUC,NaN,Nancy S,"I am loving this color. It's a pretty red, wi...",CND Hollywood,1378166400,NaN,NaN
15270,5,True,"07 7, 2014",A27OOJSY1RH1O6,B003OGV7UO,{'Color:': ' Powder My Nose'},A-Lo,Terrific nude color!,Five Stars,1404691200,3.0,NaN
29903,1,False,"08 24, 2017",A29E6HV2DT7RCI,B017UMXLTM,NaN,Onecutepoohbear,Felt like baby oil. Very heavy on the skin. Br...,Broke my face out,1503532800,NaN,NaN
9253,5,True,"06 11, 2015",A3K7RVCWO9MZQL,B0015Z90NC,NaN,carina,It is useful as it described.,Five Stars,1433980800,NaN,NaN

In [29]:
# Count the distribution of 'overall' ratings
rating_distribution2 = df2_sampled['overall'].value_counts().sort_index()

print("Distribution of Overall Ratings:")
print(rating_distribution2)

Distribution of Overall Ratings:
overall
1     463
2     642
3    1663
4    3395
5    8837
Name: count, dtype: int64

In [30]:
# drop all columns except the id review text and overall
df2_sampled_2 = df2_sampled[['overall', 'reviewText']]
df2_sampled_2.head()

       overall                                         reviewText
27291        4  DH got his first bottle of Baxter of Californi...
16095        5  I am loving this color.  It's a pretty red, wi...
15270        5                               Terrific nude color!
29903        1  Felt like baby oil. Very heavy on the skin. Br...
9253         5                      It is useful as it described.