# **Importing the dataset**

## Digital Music

In [15]:
import pandas as pd

# Load a JSON file into a pandas DataFrame
df = pd.read_json('/content/Digital_Music_5.json', lines=True)

df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image
0,5,3.0,True,"06 3, 2013",A2TYZ821XXK2YZ,3426958910,{'Format:': ' Audio CD'},Garrett,"This is awesome to listen to, A must-have for ...",Slayer Rules!,1370217600,NaN
1,5,NaN,True,"10 11, 2014",A3OFSREZADFUDY,3426958910,{'Format:': ' Audio CD'},Ad,bien,Five Stars,1412985600,NaN
2,5,NaN,True,"02 11, 2014",A2VAMODP8M77NG,3426958910,{'Format:': ' Audio CD'},JTGabq,It was great to hear the old stuff again and I...,SLAYER!!!!!!!!!!!!!!!!!!!!!,1392076800,NaN
3,4,3.0,False,"12 7, 2013",AAKSLZ9IDTEH0,3426958910,{'Format:': ' Audio CD'},john F&#039;n doe,well best of's are a bit poison normally but t...,slayer greatest hits! you mean everything righ...,1386374400,NaN
4,5,NaN,True,"06 12, 2016",A3OH43OZJLKI09,5557706259,{'Format:': ' Audio CD'},melinda a goodman,What can I say? This is Casting Crowns!!!This ...,"This is a good, blessing filled",1465689600,NaN

In [16]:
print(f"The DataFrame has {df.shape[0]} rows and {df.shape[1]} columns.")

The DataFrame has 169781 rows and 12 columns.

In [17]:
# Randomly sample 15,000 rows
df_sampled = df.sample(n=15000, random_state=42) # Using random_state for reproducibility

print(f"The sampled DataFrame has {df_sampled.shape[0]} rows and {df_sampled.shape[1]} columns.")
df_sampled.head()

The sampled DataFrame has 15000 rows and 12 columns.

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image
89071,5,NaN,True,"10 23, 2014",A2C2S9BBPWTK9Y,B00CZF8B68,{'Format:': ' MP3 Music'},Suzi,"Love the movie, and especially the song!",Five Stars,1414022400,NaN
131119,5,NaN,False,"12 31, 2015",AQR5ZB4BIJFLT,B00122Z6ZY,{'Format:': ' MP3 Music'},jackie,"Sigh, so good!",so good!,1451520000,NaN
116727,5,NaN,True,"04 18, 2016",A3QEOGJXHI6UEG,B0186SEPNU,{'Format:': ' MP3 Music'},Irene Garcia,Love the foo fighters,Five Stars,1460937600,NaN
76480,5,NaN,True,"12 3, 2014",A18REVWRZ4GA7M,B007JCPEVM,{'Format:': ' MP3 Music'},wendy kipp,1,Five Stars,1417564800,NaN
160338,5,NaN,True,"02 11, 2015",A2IJCEG2J34W61,B00E67KLDE,{'Format:': ' MP3 Music'},Honest Critique,Great Song.,Five Stars,1423612800,NaN

In [18]:
# Count the distribution of 'overall' ratings
rating_distribution = df_sampled['overall'].value_counts().sort_index()

print("Distribution of Overall Ratings:")
print(rating_distribution)

Distribution of Overall Ratings:
overall
1      191
2      156
3      606
4     2037
5    12010
Name: count, dtype: int64

In [19]:
# drop all columns except the id review text and overall
df_sampled_2 = df_sampled[['overall', 'reviewText']]

In [14]:
df_sampled_2.head()

        overall                                reviewText
89071         5  Love the movie, and especially the song!
131119        5                            Sigh, so good!
116727        5                     Love the foo fighters
76480         5                                         1
160338        5                               Great Song.